# Generated by Django 6.0.3 on 2026-04-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='active_school_year',
            field=models.CharField(default='2025-2026', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='grading_system',
            field=models.CharField(default='75 (Standard)', max_length=50),
        ),
    ]
