# Generated by Django 6.0.3 on 2026-03-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='standing',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Conditional', 'Conditional'), ('At Risk', 'At Risk')], default='Regular', max_length=20),
        ),
    ]
