# Generated by Django 6.0.3 on 2026-03-27 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('grading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('Quiz', 'Quiz'), ('Activity', 'Activity'), ('Exam', 'Exam'), ('Project', 'Project')], default='Activity', max_length=20),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='days_of_week',
            field=models.CharField(blank=True, help_text='e.g., M-W-F or T-Th', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PeriodGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('computed_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_grades', to='grading.enrollment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.period')),
            ],
            options={
                'unique_together': {('enrollment', 'period')},
            },
        ),
    ]
