# Generated by Django 6.0.3 on 2026-03-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grading', '0002_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='days',
            field=models.CharField(blank=True, default='TBA', max_length=100, null=True),
        ),
    ]
